
# This script is designed to restore missing assets for the Canvus application.
# It reads a CSV report that lists assets identified as missing and attempts to
# copy them from a specified backup location to the Canvus assets directory.
# This script is safe to run and only performs file copy operations based on
# the provided CSV report. It does not modify system settings or install software.

# Define the base directory where Canvus assets are stored.
# This is a standard installation path for Canvus assets.
$AssetsDirectory = "C:\\ProgramData\\MultiTaction\\canvus\\assets"
Write-Host "Using default assets directory: $AssetsDirectory"

# Define the path to the CSV report containing information about missing assets.
    # This file is expected to be generated by a separate reporting process and located
    # in the same directory from which this script is executed.
$csvPath = "missing_assets.csv"
# Check if the CSV report file exists.
# If the file is not found, an error message is displayed, and the script exits,
# as it cannot proceed without the list of missing assets.
if (-not (Test-Path -Path $csvPath)) {
    Write-Host "Error: missing_assets.csv not found at $csvPath. Please ensure the report is generated."
    exit 1
}

# Import the CSV file into a collection of objects.
# Each row in the CSV will be treated as an object with properties corresponding to the CSV headers.
$missingAssets = Import-Csv -Path $csvPath

# Iterate through each asset listed in the CSV report.
foreach ($asset in $missingAssets) {
    # Extract the 'Hash' and 'BackupPath' for the current asset from the CSV.
    # The 'Hash' is used to construct the destination path within the Canvus assets directory.
    # The 'BackupPath' indicates where the asset is located in the backup storage.
    $hash = $asset.Hash
    $backupPath = $asset.BackupPath
    
    # Construct the full destination directory path for the asset.
    # Canvus organizes assets into subdirectories named after the first two characters of their hash.
    $destinationDir = Join-Path $AssetsDirectory $hash.Substring(0, 2)
    # Construct the full destination path for the asset, including its filename (which is its hash).
    $destinationPath = Join-Path $destinationDir $hash

    # Check if the 'BackupStatus' for the asset is "Found".
    # This ensures that we only attempt to restore assets that were successfully located in the backup.
    if ($asset.BackupStatus -eq "Found") {
        # Verify that the backup file actually exists at the reported 'BackupPath'.
        if (Test-Path -Path $backupPath) {
            # If the destination directory (e.g., C:\ProgramData\MultiTaction\canvus\assets\AB) does not exist, create it.
            # The -Force parameter ensures that parent directories are also created if they don't exist.
            if (-not (Test-Path -Path $destinationDir)) {
                New-Item -ItemType Directory -Path $destinationDir -Force
            }
            
            # Inform the user about the asset being restored.
            Write-Host "Restoring $($asset.OriginalFilename) from $backupPath to $destinationPath"
            # Copy the asset from its backup location to the Canvus assets directory.
            # The -Force parameter overwrites the destination file if it already exists.
            Copy-Item -Path $backupPath -Destination $destinationPath -Force
        } else {
            # If the backup file is reported as "Found" in the CSV but does not exist on disk, issue a warning.
            Write-Host "WARNING: Backup file not found for $($asset.OriginalFilename) at $backupPath. Please check the backup source."
        }
    }
}

# Script completion message.
Write-Host "Asset restoration script finished. Please review any warnings above."
